//
// Created by Administrator on 2023/10/26 0026.
//

#ifndef JUSTPLAYER_JUSTMEDIACODECPLAYER_H
#define JUSTPLAYER_JUSTMEDIACODECPLAYER_H


class JustMediaCodecPlayer {

};


#endif //JUSTPLAYER_JUSTMEDIACODECPLAYER_H
